# -*- coding: utf-8 -*-
"""Súmulas TST 401-463"""

SUMULAS_5 = [
    {
        "numero": 401,
        "titulo": "AÇÃO RESCISÓRIA. DESCONTOS LEGAIS. FASE DE EXECUÇÃO. SENTENÇA EXEQUENDA. INEXISTÊNCIA DE OFENSA À COISA JULGADA",
        "texto": "Os descontos previdenciários e fiscais devem ser efetuados pelo juízo executório, ainda que a sentença exequenda tenha sido omissa sobre a questão, dado o caráter de ordem pública ostentado pela norma que os disciplina. A ofensa à coisa julgada somente poderá ser caracterizada na hipótese de o título exequendo, expressamente, afastar a dedução dos valores a título de imposto de renda e de contribuição previdenciária.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Execução Trabalhista",
        "legislacao": ["CLT, art. 832", "Lei 8.212/1991", "CF/1988, art. 5º, XXXVI"]
    },
    {
        "numero": 402,
        "titulo": "AÇÃO RESCISÓRIA. DOCUMENTO NOVO. DISSÍDIO COLETIVO. SENTENÇA NORMATIVA",
        "texto": "I – Para efeitos do art. 966, VII, do CPC de 2015 (art. 485, VII, do CPC de 1973), documento novo é o cronologicamente velho, já existente ao tempo da decisão rescindenda, mas ignorado pelo interessado ou de impossível utilização, à época em que foi proferida a decisão rescindenda.\nII – Não é documento novo apto a viabilizar a desconstituição de julgado:\na) sentença normativa proferida ou transitada em julgado posteriormente à sentença rescindenda;\nb) sentença normativa preexistente à sentença rescindenda, mas não exibida no processo principal, em virtude de negligência da parte, quando podia e deveria louvar-se de tal documento.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 966, VII"]
    },
    {
        "numero": 403,
        "titulo": "AÇÃO RESCISÓRIA. INÉPCIA DA PETIÇÃO INICIAL. CAUSA DE PEDIR. AUSÊNCIA OU NÃO ADEQUAÇÃO DO FUNDAMENTO LEGAL",
        "texto": "I – É inepta a petição inicial de ação rescisória que não obedece ao disposto no art. 968, I, do CPC de 2015 (art. 488, I, do CPC de 1973), por ausência de causa de pedir, ou seja, não expõe o vício que vulnera a coisa julgada.\nII – A causa de pedir na ação rescisória é de ser interpretada de forma ampla, não ficando adstrita ao fundamento legal apontado pelo autor, desde que se possa extrair dos fatos narrados na petição inicial a configuração de uma das hipóteses previstas nos incisos do art. 966 do CPC de 2015 (art. 485 do CPC de 1973).\nIII – O enquadramento legal dado pelo demandante não delimita a prestação jurisdicional nas ações rescisórias, podendo o Tribunal considerá-lo em sua amplitude.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 966", "CPC de 2015, art. 968"]
    },
    {
        "numero": 404,
        "titulo": "AÇÃO RESCISÓRIA. FUNDAMENTO PARA INVALIDAR CONFISSÃO. CONFISSÃO FICTA. INADEQUAÇÃO DO ENQUADRAMENTO NO ART. 966, VIII, DO CPC DE 2015",
        "texto": "I – Em fase rescisória, o vício de confissão previsto no art. 966, VIII, do CPC de 2015 (art. 485, VIII, do CPC de 1973) não pode ser invocado para impugnar confissão ficta, por não se tratar de ato atribuído à parte.\nII – Também não pode ser invocado para impugnar confissão real, com fundamento em coação, quando não alegada em momento oportuno no processo principal.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 966, VIII"]
    },
    {
        "numero": 405,
        "titulo": "AÇÃO RESCISÓRIA. LIMITAÇÃO TEMPORAL. INAPLICABILIDADE DE ORIENTAÇÃO JURISPRUDENCIAL POSTERIOR AO TRÂNSITO EM JULGADO",
        "texto": "A criação superveniente de Orientação Jurisprudencial pelo TST, ocorrida após o trânsito em julgado da decisão rescindenda, não autoriza a propositura de ação rescisória.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 966"]
    },
    {
        "numero": 406,
        "titulo": "AÇÃO RESCISÓRIA. LITISCONSÓRCIO NECESSÁRIO. CÔNJUGE",
        "texto": "I – Afigura-se desnecessária a citação do cônjuge como litisconsorte necessário para a rescisão de sentença proferida com base em confissão ficta de efeitos patrimoniais do outro cônjuge.\nII – O cônjuge deverá ser necessariamente citado como litisconsorte passivo na ação rescisória quando tiver participado do processo principal.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 114"]
    },
    {
        "numero": 407,
        "titulo": "AÇÃO RESCISÓRIA. MINISTÉRIO PÚBLICO. LEGITIMIDADE \"AD CAUSAM\" PREVISTA NO ART. 967, III, \"A\", \"B\" E \"C\" DO CPC DE 2015. HIPÓTESES MERAMENTE EXEMPLIFICATIVAS",
        "texto": "A legitimidade do Ministério Público para propor ação rescisória, ainda que não tenha sido parte no processo que deu origem à decisão rescindenda, não está limitada às hipóteses expressamente previstas no art. 967, III, do CPC de 2015 (art. 487, III, do CPC de 1973), sendo admissível em outras situações em que a decisão seja contrária ao interesse ou à ordem pública.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 967, III"]
    },
    {
        "numero": 408,
        "titulo": "AÇÃO RESCISÓRIA. PETIÇÃO INICIAL. CAUSA DE PEDIR. VIOLAÇÃO DE LEI",
        "texto": "Não padece de inépcia a petição inicial de ação rescisória apenas porque o autor indicou, na causa de pedir, dispositivo de lei federal diferente daquele que o Tribunal considerou violado ao pronunciar o juízo rescindente. Contudo, para o iudicium rescissorium, o Tribunal adstringir-se-á à causa de pedir enunciada na inicial.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 966, V"]
    },
    {
        "numero": 409,
        "titulo": "AÇÃO RESCISÓRIA. PRAZO. SENTENÇA. RECURSO VOLUNTÁRIO NÃO ADMITIDO",
        "texto": "Proposta ação rescisória pelo réu antes do trânsito em julgado para o autor, aplica-se o disposto no parágrafo único do art. 975 do CPC de 2015 (§ 3º do art. 495 do CPC de 1973), quando, no julgamento do recurso do autor, obtiver ele resultado favorável.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 975"]
    },
    {
        "numero": 410,
        "titulo": "AÇÃO RESCISÓRIA. PRAZO. TERMO INICIAL. TRÂNSITO EM JULGADO PROGRESSIVO",
        "texto": "Não obsta o ajuizamento de ação rescisória o fato de a decisão rescindenda ainda ser objeto de impugnação ante o Tribunal Superior do Trabalho pelo recurso de embargos ou de recurso extraordinário, salvo se a parte pretende desconstituir capítulo transitado em julgado.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 975"]
    },
    {
        "numero": 411,
        "titulo": "AÇÃO RESCISÓRIA. SENTENÇA DE MÉRITO. QUESTÃO PROCESSUAL",
        "texto": "O vício que autoriza a rescisão do julgado trabalhista há de ser claro, manifesto, suscetível de identificação segura. Não é admissível ação rescisória de decisão onde o trânsito em julgado formal e material seja duvidoso.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 966"]
    },
    {
        "numero": 412,
        "titulo": "AÇÃO RESCISÓRIA. TUTELA ANTECIPADA. CABIMENTO",
        "texto": "Nas ações rescisórias, o cabimento de tutela antecipada é pertinente quando presentes os pressupostos do art. 300 do CPC de 2015 (art. 273 do CPC de 1973).",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Ação Rescisória",
        "legislacao": ["CPC de 2015, art. 300"]
    },
    {
        "numero": 413,
        "titulo": "HORAS EXTRAS. GORJETAS. NÃO INTEGRAÇÃO NA BASE DE CÁLCULO",
        "texto": "Gorjetas não integram o valor do salário para efeito de cálculo das horas extras.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Remuneração",
        "legislacao": ["CLT, art. 457", "CLT, art. 64"]
    },
    {
        "numero": 414,
        "titulo": "MANDADO DE SEGURANÇA. ANTECIPAÇÃO DE TUTELA (OU LIMINAR) CONCEDIDA ANTES OU NA SENTENÇA",
        "texto": "I – A antecipação de tutela concedida na sentença não comporta impugnação pela via do mandado de segurança, por ser impugnável mediante recurso ordinário. A ação cautelar é o meio próprio para se obter efeito suspensivo a recurso.\nII – No caso da tutela antecipada (ou liminar) ser concedida antes da sentença, cabe a impetração do mandado de segurança, em face da inexistência de recurso próprio.\nIII – A superveniência da sentença, nos autos originários, faz perder o objeto do mandado de segurança que impugnava a concessão da tutela antecipada (ou liminar).",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Mandado de Segurança",
        "legislacao": ["CLT, art. 899", "CPC de 2015, art. 300", "Lei 12.016/2009"]
    },
    {
        "numero": 415,
        "titulo": "MANDADO DE SEGURANÇA. IMPUGNAÇÃO DE DECISÃO INTERLOCUTÓRIA. CABIMENTO",
        "texto": "Mandado de segurança não é o meio adequado para impugnar decisão interlocutória, ainda que esta cause lesão grave e de difícil reparação.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Mandado de Segurança",
        "legislacao": ["CLT, art. 893", "Lei 12.016/2009"]
    },
    {
        "numero": 416,
        "titulo": "MANDADO DE SEGURANÇA. REINTEGRAÇÃO LIMINAR. VEDAÇÃO",
        "texto": "Devendo o mandado de segurança ser impetrado no prazo de 120 dias da ciência do ato, o mandado de segurança para reintegração do trabalhador demitido deve ser impetrado no prazo de 120 dias da ciência da dispensa.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Mandado de Segurança",
        "legislacao": ["Lei 12.016/2009, art. 23"]
    },
    {
        "numero": 417,
        "titulo": "MANDADO DE SEGURANÇA. PENHORA EM DINHEIRO. ATO COATOR. IMPUGNAÇÃO",
        "texto": "I – Não fere direito líquido e certo do impetrante o ato judicial que determina penhora em dinheiro do executado, em execução definitiva, para garantir crédito exequendo, uma vez que obedecida a gradação prevista no art. 835 do CPC de 2015 (art. 655 do CPC de 1973).\nII – Quando se tratar de execução provisória, fere direito líquido e certo do impetrante a determinação de penhora em dinheiro, quando nomeados outros bens à penhora, pois o executado tem direito a que a execução se processe da forma que lhe seja menos gravosa, nos termos do art. 805 do CPC de 2015 (art. 620 do CPC de 1973).\n(Item III cancelado)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Mandado de Segurança",
        "legislacao": ["CPC de 2015, art. 835", "CPC de 2015, art. 805", "Lei 12.016/2009"]
    },
    {
        "numero": 418,
        "titulo": "MANDADO DE SEGURANÇA VISANDO À HOMOLOGAÇÃO DE ACORDO",
        "texto": "A homologação de acordo constitui faculdade do juiz, inexistindo direito líquido e certo tutelável pela via do mandado de segurança.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Mandado de Segurança",
        "legislacao": ["Lei 12.016/2009"]
    },
    {
        "numero": 419,
        "titulo": "COMPETÊNCIA. EMBARGOS DE TERCEIRO. EXECUÇÃO POR CARTA PRECATÓRIA",
        "texto": "Na execução por carta precatória, os embargos de terceiro serão oferecidos no juízo deprecado, salvo se indicado pelo juízo deprecante o bem constrito ou se já devolvida a carta (art. 676, parágrafo único, do CPC de 2015).",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Competência",
        "legislacao": ["CPC de 2015, art. 676"]
    },
    {
        "numero": 420,
        "titulo": "COMPETÊNCIA FUNCIONAL. CONFLITO NEGATIVO. TRT E VARA DO TRABALHO DE IDÊNTICA REGIÃO",
        "texto": "Não se configura conflito de competência entre Tribunal Regional do Trabalho e Vara do Trabalho a ele vinculada.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Competência",
        "legislacao": ["CLT, art. 808"]
    },
    {
        "numero": 421,
        "titulo": "EMBARGOS DE DECLARAÇÃO. CABIMENTO. DECISÃO MONOCRÁTICA DO RELATOR CALCADA NO ART. 932 DO CPC DE 2015",
        "texto": "I – Cabem embargos de declaração da decisão monocrática do relator prevista no art. 932 do CPC de 2015 (art. 557 do CPC de 1973), se a parte pretende tão somente integrar a decisão com o intuito de prequestionar a matéria para fins de interposição de outros recursos.\nII – Não cabem embargos de declaração quando se busca apenas compelir o Relator a submeter a questão ao colegiado.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CPC de 2015, art. 932"]
    },
    {
        "numero": 422,
        "titulo": "RECURSO. FUNDAMENTO AUSENTE OU DEFICIENTE. NÃO CONHECIMENTO",
        "texto": "I – Não se conhece de recurso para o TST, pela ausência do requisito de admissibilidade inscrito no art. 1.010, II e III, do CPC de 2015 (art. 514, II, do CPC de 1973), quando as razões do recorrente não impugnam os fundamentos da decisão recorrida, nos termos em que fora proposta.\nII – O entendimento referido no item anterior não se aplica quando a parte não está representada por advogado.\nIII – Inaplicável a Súmula 422 do TST quando o recurso versar sobre incompetência relativa.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CPC de 2015, art. 1.010"]
    },
    {
        "numero": 423,
        "titulo": "TURNO ININTERRUPTO DE REVEZAMENTO. FIXAÇÃO DE JORNADA DE TRABALHO MEDIANTE NEGOCIAÇÃO COLETIVA. VALIDADE",
        "texto": "Cancelada em razão da decisão do STF no ARE 1.121.633, por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 7º, XIV", "CF/1988, art. 7º, XIV"]
    },
    {
        "numero": 424,
        "titulo": "RECURSO ADMINISTRATIVO. PRESSUPOSTO DE ADMISSIBILIDADE. DEPÓSITO PRÉVIO DA MULTA ADMINISTRATIVA",
        "texto": "O §1º do art. 636 da CLT, que estabelece a exigência de prova do depósito prévio do valor da multa cominada em razão de autuação administrativa como pressuposto de admissibilidade de recurso administrativo, não foi recepcionado pela Constituição Federal de 1988, ante a sua incompatibilidade com o inciso LV do art. 5º.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Administrativo do Trabalho",
        "tema": "Processo Administrativo",
        "legislacao": ["CLT, art. 636", "CF/1988, art. 5º, LV"]
    },
    {
        "numero": 425,
        "titulo": "JUS POSTULANDI NA JUSTIÇA DO TRABALHO. ALCANCE",
        "texto": "O jus postulandi das partes, estabelecido no art. 791 da CLT, limita-se às Varas do Trabalho e aos Tribunais Regionais do Trabalho, não alcançando a ação rescisória, a ação cautelar, o mandado de segurança e os recursos de competência do Tribunal Superior do Trabalho.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Representação Processual",
        "legislacao": ["CLT, art. 791"]
    },
    {
        "numero": 426,
        "titulo": "DEPÓSITO RECURSAL. UTILIZAÇÃO DA GUIA GFIP. OBRIGATORIEDADE",
        "texto": "Cancelada em razão das alterações promovidas pela Lei 13.467/2017 (Reforma Trabalhista), por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CLT, art. 899"]
    },
    {
        "numero": 427,
        "titulo": "INTIMAÇÃO. PLURALIDADE DE ADVOGADOS. PUBLICAÇÃO EM NOME DE ADVOGADO DIVERSO DAQUELE EXPRESSAMENTE INDICADO",
        "texto": "Havendo pedido expresso de que as intimações e publicações sejam realizadas exclusivamente em nome de determinado advogado, a comunicação em nome de outro profissional constituído nos autos é nula, salvo se constatada a inexistência de prejuízo.\n(IRR-305-05-2016-000-09-00-8, DEJT divulgado em 15, 16 e 17.05.2017)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Intimações e Notificações",
        "legislacao": ["CPC de 2015, art. 272"]
    },
    {
        "numero": 428,
        "titulo": "SOBREAVISO. APLICAÇÃO ANALÓGICA DO ART. 244, § 2º DA CLT",
        "texto": "I – O uso de instrumentos telemáticos ou informatizados fornecidos pela empresa ao empregado, por si só, não caracteriza o regime de sobreaviso.\nII – Considera-se em sobreaviso o empregado que, à distância e submetido a controle patronal por instrumentos telemáticos ou informatizados, permanecer em regime de plantão ou equivalente, aguardando a qualquer momento o chamado para o serviço durante o período de descanso.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 244, § 2º"]
    },
    {
        "numero": 429,
        "titulo": "TEMPO À DISPOSIÇÃO DO EMPREGADOR. ART. 4º DA CLT. PERÍODO DE DESLOCAMENTO ENTRE A PORTARIA E O LOCAL DE TRABALHO",
        "texto": "Cancelada em razão das alterações promovidas pela Lei 13.467/2017 (Reforma Trabalhista), por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 4º"]
    },
    {
        "numero": 430,
        "titulo": "ADMINISTRAÇÃO PÚBLICA INDIRETA. CONTRATAÇÃO. AUSÊNCIA DE CONCURSO PÚBLICO. NULIDADE. ULTERIOR PRIVATIZAÇÃO. CONVALIDAÇÃO",
        "texto": "Convalidam-se os efeitos do contrato de trabalho que, considerado nulo por ausência de concurso público, quando celebrado originalmente com ente da Administração Pública Indireta, continua a existir após a sua privatização.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Contrato de Trabalho",
        "legislacao": ["CF/1988, art. 37, II"]
    },
    {
        "numero": 431,
        "titulo": "SALÁRIO-HORA. EMPREGADO SUJEITO AO REGIME GERAL DE TRABALHO (ART. 58, CAPUT, DA CLT). 40 HORAS SEMANAIS. CÁLCULO. APLICAÇÃO DO DIVISOR 200",
        "texto": "Para os empregados a que alude o art. 58, caput, da CLT, quando sujeitos a 40 horas semanais de trabalho, aplica-se o divisor 200 (duzentos) para o cálculo do valor do salário-hora.\n(IRR-260-00-2016-000-05-00-7, DEJT divulgado em 15, 16 e 17.05.2017)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Remuneração",
        "legislacao": ["CLT, art. 58"]
    },
    {
        "numero": 432,
        "titulo": "CONTRIBUIÇÃO SINDICAL RURAL. AÇÃO DE COBRANÇA. PENALIDADE POR ATRASO NO RECOLHIMENTO",
        "texto": "O recolhimento a destempo da contribuição sindical rural não acarreta a aplicação da multa progressiva prevista no art. 600 da CLT, em decorrência da sua revogação tácita pela Lei nº 8.022, de 12 de abril de 1990.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Coletivo do Trabalho",
        "tema": "Contribuição Sindical",
        "legislacao": ["CLT, art. 600", "Lei 8.022/1990"]
    },
    {
        "numero": 433,
        "titulo": "EMBARGOS. ADMISSIBILIDADE. PROCESSO EM FASE DE EXECUÇÃO. ACÓRDÃO DE TURMA PUBLICADO NA VIGÊNCIA DA LEI Nº 11.496",
        "texto": "A causa, na fase de execução, não se insere no conceito de \"causas decididas\" para fins do cabimento dos embargos de divergência para o TST, nos termos do art. 894, II, da CLT, com a redação dada pela Lei nº 11.496/2007. Somente na fase de conhecimento é cabível o recurso de embargos para o TST.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CLT, art. 894, II", "Lei 11.496/2007"]
    },
    {
        "numero": 434,
        "titulo": "RECURSO. INTERPOSIÇÃO ANTES DA PUBLICAÇÃO DO ACÓRDÃO IMPUGNADO. EXTEMPORANEIDADE",
        "texto": "Cancelada.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CLT, art. 893"]
    },
    {
        "numero": 435,
        "titulo": "DECISÃO MONOCRÁTICA. RELATOR. ART. 932 DO CPC DE 2015",
        "texto": "Aplica-se subsidiariamente ao processo do trabalho o art. 932 do CPC de 2015 (art. 557 do CPC de 1973).",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CPC de 2015, art. 932"]
    },
    {
        "numero": 436,
        "titulo": "REPRESENTAÇÃO PROCESSUAL. PROCURADOR DA UNIÃO, ESTADOS, MUNICÍPIOS E DISTRITO FEDERAL",
        "texto": "I – A União, Estados, Municípios e Distrito Federal, suas autarquias e fundações públicas, quando representadas em juízo, ativa e passivamente, por seus procuradores, estão dispensadas da juntada de instrumento de mandato e de comprovação do ato de nomeação.\nII – Para os efeitos do item anterior, é necessário que o signatário declare, na própria peça, sua condição de representante judicial da parte.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Representação Processual",
        "legislacao": ["CPC de 2015, art. 75"]
    },
    {
        "numero": 437,
        "titulo": "INTERVALO INTRAJORNADA PARA REPOUSO E ALIMENTAÇÃO. APLICAÇÃO DO ART. 71 DA CLT",
        "texto": "Cancelada em razão das alterações promovidas pela Lei 13.467/2017 (Reforma Trabalhista), por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 71"]
    },
    {
        "numero": 438,
        "titulo": "INTERVALO PARA RECUPERAÇÃO TÉRMICA DO EMPREGADO. AMBIENTE ARTIFICIALMENTE FRIO",
        "texto": "O empregado submetido a trabalho contínuo em ambiente artificialmente frio, nos termos do parágrafo único do art. 253 da CLT, ainda que não labore em câmara frigorífica, tem direito ao intervalo intrajornada previsto no caput do art. 253 da CLT.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Saúde e Segurança do Trabalho",
        "legislacao": ["CLT, art. 253"]
    },
    {
        "numero": 439,
        "titulo": "DANOS MORAIS. JUROS DE MORA E ATUALIZAÇÃO MONETÁRIA. TERMO INICIAL",
        "texto": "Cancelada em razão das decisões do STF nas ADI 5867, ADI 6012, ADC 58 e ADC 59, por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Responsabilidade Civil",
        "legislacao": ["CLT, art. 879"]
    },
    {
        "numero": 440,
        "titulo": "AUXÍLIO-DOENÇA ACIDENTÁRIO. APOSENTADORIA POR INVALIDEZ. SUSPENSÃO DO CONTRATO DE TRABALHO. RECONHECIMENTO DO DIREITO À MANUTENÇÃO DE PLANO DE SAÚDE OU DE ASSISTÊNCIA MÉDICA",
        "texto": "Assegura-se o direito à manutenção de plano de saúde ou de assistência médica oferecido pela empresa ao empregado, não obstante suspenso o contrato de trabalho em virtude de auxílio-doença acidentário ou de aposentadoria por invalidez.\n(IRR-220-00-2013-000-12-00-6, DEJT divulgado em 14, 15 e 16.10.2014)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Benefícios ao Trabalhador",
        "legislacao": ["CLT, art. 476"]
    },
    {
        "numero": 441,
        "titulo": "AVISO PRÉVIO. PROPORCIONALIDADE",
        "texto": "O direito ao aviso prévio proporcional ao tempo de serviço somente é assegurado nas rescisões de contrato de trabalho ocorridas a partir da publicação da Lei nº 12.506, em 13 de outubro de 2011.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Rescisão Contratual",
        "legislacao": ["Lei 12.506/2011", "CLT, art. 487"]
    },
    {
        "numero": 442,
        "titulo": "PROCEDIMENTO SUMARÍSSIMO. RECURSO DE REVISTA FUNDAMENTADO EM CONTRARIEDADE A ORIENTAÇÃO JURISPRUDENCIAL",
        "texto": "Nas causas sujeitas ao procedimento sumaríssimo, a admissibilidade de recurso de revista está limitada à demonstração de violação direta a dispositivo da Constituição Federal ou contrariedade a Súmula do Tribunal Superior do Trabalho, não se admitindo o recurso por contrariedade a Orientação Jurisprudencial deste Tribunal (Livro II, Título II, Capítulo III, do RITST).",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CLT, art. 896, § 6º"]
    },
    {
        "numero": 443,
        "titulo": "DISPENSA DISCRIMINATÓRIA. PRESUNÇÃO. EMPREGADO PORTADOR DE DOENÇA GRAVE",
        "texto": "Presume-se discriminatória a despedida de empregado portador do vírus HIV ou de outra doença grave que suscite estigma ou preconceito. Inválido o ato, o empregado tem direito à reintegração no emprego.\n(IRR-254-00-2012-000-17-00-8, DEJT divulgado em 25, 26 e 27.05.2016)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Dispensa e Reintegração",
        "legislacao": ["Lei 9.029/1995", "CF/1988, art. 1º, III"]
    },
    {
        "numero": 444,
        "titulo": "JORNADA DE TRABALHO. NORMA COLETIVA. LEI. ESCALA DE 12 POR 36. VALIDADE",
        "texto": "Cancelada em razão das alterações promovidas pela Lei 13.467/2017 (Reforma Trabalhista), por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 59", "CF/1988, art. 7º, XIII"]
    },
    {
        "numero": 445,
        "titulo": "INADIMPLEMENTO DE VERBAS TRABALHISTAS. FRUTOS. POSSE DE MÁ-FÉ",
        "texto": "A indenização por frutos percebidos pela posse de má-fé, prevista no art. 1.216 do Código Civil, por tratar-se de regra afeta a direitos reais, mostra-se incompatível com o Direito do Trabalho, não sendo devida no caso de inadimplemento de verbas trabalhistas.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Remuneração",
        "legislacao": ["Código Civil, art. 1.216"]
    },
    {
        "numero": 446,
        "titulo": "MAQUINISTA FERROVIÁRIO. INTERVALO INTRAJORNADA. SUPRESSÃO PARCIAL OU TOTAL",
        "texto": "A garantia ao intervalo intrajornada, prevista no art. 71 da CLT, por constituir-se em medida de higiene, saúde e segurança do empregado, é aplicável também ao ferroviário maquinista integrante da categoria \"c\", assim definida no art. 1º do Decreto nº 16.107/1923, sendo inválida a cláusula de acordo ou convenção coletiva de trabalho contemplando sua supressão ou redução.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 71", "Decreto 16.107/1923"]
    },
    {
        "numero": 447,
        "titulo": "ADICIONAL DE PERICULOSIDADE. PERMANÊNCIA A BORDO DURANTE O ABASTECIMENTO DA AERONAVE. INDEVIDO",
        "texto": "Os tripulantes e demais empregados em serviços auxiliares de transporte aéreo que, no momento do abastecimento da aeronave, permanecem a bordo não têm direito ao adicional de periculosidade a que alude o art. 193 da CLT.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Saúde e Segurança do Trabalho",
        "legislacao": ["CLT, art. 193"]
    },
    {
        "numero": 448,
        "titulo": "ATIVIDADE INSALUBRE. CARACTERIZAÇÃO. PREVISÃO NA NORMA REGULAMENTADORA Nº 15",
        "texto": "I – Não basta a constatação da insalubridade por meio de laudo pericial para que o empregado tenha direito ao respectivo adicional, sendo necessária a classificação da atividade insalubre na relação oficial elaborada pelo Ministério do Trabalho.\nII – A higienização de instalações sanitárias de uso público ou coletivo de grande circulação, e a respectiva coleta de lixo, por não se equiparar à limpeza em residências e escritórios, é classificada como atividade insalubre em grau máximo, conforme a NR 15 do Ministério do Trabalho.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Saúde e Segurança do Trabalho",
        "legislacao": ["CLT, art. 189", "CLT, art. 190"]
    },
    {
        "numero": 449,
        "titulo": "MINUTOS QUE ANTECEDEM E SUCEDEM A JORNADA DE TRABALHO",
        "texto": "Cancelada em razão das alterações promovidas pela Lei 13.467/2017 (Reforma Trabalhista), por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Jornada de Trabalho",
        "legislacao": ["CLT, art. 58, § 1º"]
    },
    {
        "numero": 450,
        "titulo": "FÉRIAS. GOZO NA ÉPOCA PRÓPRIA. PAGAMENTO FORA DO PRAZO. DOBRA DEVIDA",
        "texto": "Cancelada em razão da decisão do STF na ADPF 501, por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Férias",
        "legislacao": ["CLT, art. 137"]
    },
    {
        "numero": 451,
        "titulo": "PARTICIPAÇÃO NOS LUCROS E RESULTADOS. RESCISÃO CONTRATUAL ANTERIOR À DATA DA DISTRIBUIÇÃO DOS LUCROS",
        "texto": "Fere o princípio da isonomia instituir vantagem mediante acordo coletivo ou norma regulamentar que condiciona a percepção da parcela participação nos lucros e resultados ao fato de estar o contrato de trabalho em vigor na data prevista para a distribuição dos lucros, premiando, assim, os empregados que permaneceram na empresa nessa data em detrimento dos que foram dispensados anteriormente.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Remuneração",
        "legislacao": ["Lei 10.101/2000", "CF/1988, art. 5º, caput"]
    },
    {
        "numero": 452,
        "titulo": "DIFERENÇAS SALARIAIS. PLANO DE CARGOS E SALÁRIOS. DESCUMPRIMENTO. CRITÉRIOS DE PROMOÇÃO NÃO OBSERVADOS. PRESCRIÇÃO PARCIAL",
        "texto": "Cancelada em razão das alterações promovidas pela Lei 13.467/2017 (Reforma Trabalhista), por meio da Resolução 225/2025.",
        "situacao": "cancelada",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Remuneração",
        "legislacao": ["CLT, art. 7º", "CLT, art. 461"]
    },
    {
        "numero": 453,
        "titulo": "ADICIONAL DE PERICULOSIDADE. PAGAMENTO ESPONTÂNEO. CARACTERIZAÇÃO DE FATO INCONTROVERSO",
        "texto": "O pagamento de adicional de periculosidade efetuado por mera liberalidade da empresa, ainda que de forma proporcional ao tempo de exposição ao risco ou em percentual inferior ao máximo legalmente previsto, dispensa a realização da prova técnica exigida pelo art. 195 da CLT, pois torna incontroversa a existência do trabalho em condições perigosas.\n(IRR-266-62-2014-000-17-00-0, DEJT divulgado em 15, 16 e 17.05.2017)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Saúde e Segurança do Trabalho",
        "legislacao": ["CLT, art. 193", "CLT, art. 195"]
    },
    {
        "numero": 454,
        "titulo": "COMPETÊNCIA DA JUSTIÇA DO TRABALHO. EXECUÇÃO DE OFÍCIO. CONTRIBUIÇÃO SOCIAL REFERENTE AO SEGURO DE ACIDENTE DE TRABALHO (SAT)",
        "texto": "Compete à Justiça do Trabalho a execução, de ofício, da contribuição referente ao Seguro de Acidente de Trabalho (SAT), que tem natureza de contribuição para a seguridade social (arts. 114, VIII, e 195, I, \"a\", da CF), pois se destina ao financiamento de benefício relativo à incapacidade laborativa decorrente de risco ambiental do trabalho (art. 22, II, da Lei nº 8.212/1991).\n(IRR-229-21-2013-000-14-00-7, DEJT divulgado em 14, 15 e 16.10.2014)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Competência",
        "legislacao": ["CF/1988, art. 114, VIII", "CF/1988, art. 195, I", "Lei 8.212/1991, art. 22, II"]
    },
    {
        "numero": 455,
        "titulo": "EQUIPARAÇÃO SALARIAL. SOCIEDADE DE ECONOMIA MISTA. ART. 37, XIII, DA CF/1988. POSSIBILIDADE",
        "texto": "À sociedade de economia mista não se aplica a vedação à equiparação prevista no art. 37, XIII, da CF/1988, pois, ao admitir empregados sob o regime da CLT, equipara-se a empregador privado, conforme disposto no art. 173, § 1º, II, da CF/1988.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Remuneração",
        "legislacao": ["CF/1988, art. 37, XIII", "CF/1988, art. 173, § 1º, II", "CLT, art. 461"]
    },
    {
        "numero": 456,
        "titulo": "REPRESENTAÇÃO. PESSOA JURÍDICA. PROCURAÇÃO. INVALIDADE. IDENTIFICAÇÃO DO OUTORGANTE E DE SEU REPRESENTANTE",
        "texto": "I – É inválida a procuração conferida por pessoa jurídica quando não identificada a pessoa física responsável pela outorga.\nII – Só é válida a procuração outorgada por pessoa jurídica se nela constar a identificação do representante legal da empresa, pois, do contrário, não há como verificar se a pessoa que confeccionou o instrumento tem poderes para tanto.\nIII – É válida a procuração assinada por diretor que se declare como tal na própria procuração, independentemente de instrumento constitutivo da empresa, somente quando a função exercida pelo outorgante for de notório conhecimento.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Representação Processual",
        "legislacao": ["CPC de 2015, art. 105"]
    },
    {
        "numero": 457,
        "titulo": "HONORÁRIOS PERICIAIS. BENEFICIÁRIO DA JUSTIÇA GRATUITA. RESPONSABILIDADE DA UNIÃO PELO PAGAMENTO",
        "texto": "A União é responsável pelo pagamento dos honorários de perito quando a parte sucumbente no objeto da perícia for beneficiária da assistência judiciária gratuita, observado o procedimento disposto nos arts. 1º, 2º e 5º da Resolução nº 66/2010 do Conselho Superior da Justiça do Trabalho – CSJT.\n(IRR-188-10-2013-000-04-00-7, DEJT divulgado em 14, 15 e 16.10.2014)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Honorários Periciais",
        "legislacao": ["CLT, art. 790-B", "Lei 5.584/1970"]
    },
    {
        "numero": 458,
        "titulo": "EMBARGOS. PROCEDIMENTO SUMARÍSSIMO. CONHECIMENTO. RECURSO INTERPOSTO APÓS VIGÊNCIA DA LEI Nº 11.496, DE 22.06.2007",
        "texto": "Em causas sujeitas ao procedimento sumaríssimo, em que o recurso de revista não é admissível por violação a norma jurídica infraconstitucional, nos termos do § 6º do art. 896 da CLT, a divergência jurisprudencial apta a embasar o recurso de embargos há de ser demonstrada em face de decisão proferida em recursos de revista julgados pelo TST em procedimento sumaríssimo.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CLT, art. 894", "CLT, art. 896, § 6º", "Lei 11.496/2007"]
    },
    {
        "numero": 459,
        "titulo": "RECURSO DE REVISTA. NULIDADE POR NEGATIVA DE PRESTAÇÃO JURISDICIONAL",
        "texto": "O conhecimento do recurso de revista, quanto à preliminar de nulidade, por negativa de prestação jurisdicional, supõe indicação de violação do art. 832 da CLT, do art. 489 do CPC de 2015 (art. 458 do CPC de 1973) ou do art. 93, IX, da CF/1988.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Recursos Trabalhistas",
        "legislacao": ["CLT, art. 832", "CPC de 2015, art. 489", "CF/1988, art. 93, IX"]
    },
    {
        "numero": 460,
        "titulo": "VALE-TRANSPORTE. ÔNUS DA PROVA",
        "texto": "É do empregador o ônus de comprovar que o empregado não satisfaz os requisitos indispensáveis para a concessão do vale-transporte ou não pretenda fazer uso do benefício.\n(IRR-232-00-2013-000-10-00-0, DEJT divulgado em 25, 26 e 27.05.2016)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Benefícios ao Trabalhador",
        "legislacao": ["Lei 7.418/1985", "Decreto 95.247/1987"]
    },
    {
        "numero": 461,
        "titulo": "FGTS. DIFERENÇAS. RECOLHIMENTO. ÔNUS DA PROVA",
        "texto": "É do empregador o ônus da prova em relação à regularidade dos depósitos do FGTS, pois o pagamento é fato extintivo do direito do autor (art. 373, II, do CPC de 2015).\n(IRR-273-95-2014-000-17-00-3, DEJT divulgado em 15, 16 e 17.05.2017)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "FGTS",
        "legislacao": ["Lei 8.036/1990", "CPC de 2015, art. 373, II"]
    },
    {
        "numero": 462,
        "titulo": "MULTA DO ART. 477, § 8º, DA CLT. INCIDÊNCIA. RECONHECIMENTO JUDICIAL DA RELAÇÃO DE EMPREGO",
        "texto": "A circunstância de a relação de emprego ter sido reconhecida apenas em juízo não tem o condão de afastar a incidência da multa prevista no art. 477, §8º, da CLT. A referida multa não será devida apenas quando, comprovadamente, o empregado der causa à mora no pagamento das verbas rescisórias.\n(IRR-168-70-2013-000-05-00-7, DEJT divulgado em 15, 16 e 17.05.2017)",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito do Trabalho",
        "tema": "Rescisão Contratual",
        "legislacao": ["CLT, art. 477, § 8º"]
    },
    {
        "numero": 463,
        "titulo": "ASSISTÊNCIA JUDICIÁRIA GRATUITA. COMPROVAÇÃO",
        "texto": "I – A partir de 26.06.2017, para a concessão da assistência judiciária gratuita à pessoa natural, basta a declaração de hipossuficiência econômica firmada pela parte ou por seu advogado, desde que munido de procuração com poderes específicos para esse fim (art. 105 do CPC de 2015).\nII – No caso de pessoa jurídica, não basta a mera declaração: é necessária a demonstração cabal de impossibilidade de a parte arcar com as despesas do processo.",
        "situacao": "vigente",
        "orgao": "TST",
        "tipo": "sumula",
        "area": "Direito Processual do Trabalho",
        "tema": "Assistência Judiciária",
        "legislacao": ["CPC de 2015, art. 99", "CPC de 2015, art. 105", "Lei 5.584/1970"]
    },
]
